website/cooperate/urls.py
from django.contrib import admin
from django.urls import path, re_path
from . import views

app_name = 'cooperate'
urlpatterns = [
    path('', views.indexview.as_view(), name='index'),
    path('flist/', views.facultieslistview.as_view(), name='faculties_list'),
    re_path(r'^f/(?P<pk>\d+)$', views.facultiesdetailview.as_view(), name='faculties_detail'),
    path('fcreate/',views.facultiescreate.as_view(), name='faculties_create'),
    re_path(r'^f/(?P<pk>\d+)/update/$', views.facultiesupdate.as_view(), name='faculties_update'),
    re_path(r'^f/(?P<pk>\d+)/delete/$', views.facultiesdelete.as_view(), name='faculties_delete'),
    path('rlist/', views.rankerslistview.as_view(), name='rankers_list'),
    re_path(r'^r/(?P<pk>\d+)$', views.rankersdetailview.as_view(), name='rankers_detail'),
    path('rcreate/',views.rankerscreate.as_view(), name='rankers_create'),
    re_path(r'^r/(?P<pk>\d+)/update/$', views.rankersupdate.as_view(), name='rankers_update'),
    re_path(r'^r/(?P<pk>\d+)/delete/$', views.rankersdelete.as_view(), name='rankers_delete'),
    path('clist/', views.centerslistview.as_view(), name='centers_list'),
    re_path(r'^c/(?P<pk>\d+)$', views.centersdetailview.as_view(), name='centers_detail'),
    path('ccreate/',views.centerscreate.as_view(), name='centers_create'),
    re_path(r'^c/(?P<pk>\d+)/update/$', views.centersupdate.as_view(), name='centers_update'),
    re_path(r'^c/(?P<pk>\d+)/delete/$', views.centersdelete.as_view(), name='centers_delete'),
    path('slist/', views.studentslistview.as_view(), name='students_list'),
    re_path(r'^s/(?P<pk>\d+)$', views.studentsdetailview.as_view(), name='students_detail'),
    path('screate/',views.studentscreate.as_view(), name='students_create'),
    re_path(r'^s/(?P<pk>\d+)/update/$', views.studentsupdate.as_view(), name='students_update'),
    re_path(r'^s/(?P<pk>\d+)/delete/$', views.studentsdelete.as_view(), name='students_delete'),
    path('feelist/', views.feelistview.as_view(), name='fee_list'),
    re_path(r'^fee/(?P<pk>\d+)$', views.feedetailview.as_view(), name='fee_detail'),
    path('feecreate/',views.feecreate.as_view(), name='fee_create'),
    re_path(r'^fee/(?P<pk>\d+)/update/$', views.feeupdate.as_view(), name='fee_update'),
    re_path(r'^fee/(?P<pk>\d+)/delete/$', views.feedelete.as_view(), name='fee_delete'),
    path('qlist/', views.quarieslistview.as_view(), name='quaries_list'),
    re_path(r'^q/(?P<pk>\d+)$', views.quariesdetailview.as_view(), name='quaries_detail'),
    path('qcreate/',views.quariescreate.as_view(), name='quaries_create'),
    re_path(r'^q/(?P<pk>\d+)/delete/$', views.quariesdelete.as_view(), name='quaries_delete'),
    path('contact/', views.contactview.as_view(), name='contact'),
    path('ack/', views.ackview.as_view(), name='ack'),
]

website/website/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.contrib.auth import views
urlpatterns = [
    path('admin/', admin.site.urls,),
    path('', include('cooperate.urls')),
        path('accounts/login/', views.LoginView.as_view(template_name='registration/login.html'), name="login"),
    path('accounts/logout/', views.LogoutView.as_view(template_name="registration/login.html"), name='logout'),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/cooperate/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse_lazy, reverse
# Create your models here.
class quaries(models.Model):
    author = models.CharField(max_length=200)
    subject = models.CharField(max_length=400)
    email = models.EmailField()
    contact = models.PositiveIntegerField()
    text = models.TextField()
    created_data = models.DateTimeField(default = timezone.now)

    def get_absolute_url(self):
        return reverse("cooperate:ack")

    def __str__(self):
        return self.subject

class faculties(models.Model):
    name = models.CharField(max_length=250)
    collegename = models.CharField(max_length=300)
    subject = models.CharField(max_length=200)
    pic = models.ImageField(upload_to="facultypic/")
    contact = models.CharField(max_length=10)
    email = models.EmailField(default="not@provided.com")
    address = models.TextField(default="NOT_PROVIDED")
    position = models.CharField(max_length=150)
    salary = models.PositiveIntegerField(default=0)
    qualification = models.CharField(max_length=300, default="B.tech")
    center = models.CharField(max_length=250, default="Jamshedpur")

    def get_absolute_url(self):
        return reverse("cooperate:faculties_detail",kwargs={'pk':self.pk})

    def __str__(self):
        return self.name

class students(models.Model):
    name = models.CharField(max_length=250)
    pic = models.ImageField(upload_to="studentpic/")
    fathername = models.CharField(max_length=300)
    contact = models.CharField(max_length =10)
    address = models.TextField()
    email = models.EmailField()
    program = models.CharField(max_length=300)
    joinyear = models.PositiveIntegerField()
    pyear = models.PositiveIntegerField()
    feestatus = models.CharField(max_length=50, default="Not paid")
    fee = models.PositiveIntegerField()
    center = models.CharField(max_length=250)
    def get_absolute_url(self):
        return reverse("cooperate:students_detail",kwargs={'pk':self.pk})

    def __str__(self):
        return self.name

class rankers(models.Model):
    name = models.CharField(max_length=250)
    pic = models.ImageField(upload_to="studentpic/")
    achievement = models.TextField()
    rank = models.CharField(max_length=100)
    program = models.CharField(max_length=300)

    def get_absolute_url(self):
        return reverse("cooperate:rankers_detail",kwargs={'pk':self.pk})

    def __str__(self):
        return self.name

class centers(models.Model):
    name = models.CharField(max_length=400)
    place = models.CharField(max_length=200)
    address = models.TextField()
    contact = models.PositiveIntegerField()

    def get_absolute_url(self):
        return reverse("cooperate:centers_detail",kwargs={'pk':self.pk})

    def __str__(self):
        return self.name + self.place

class fee(models.Model):
    course = models.CharField(max_length=300)
    years  = models.PositiveIntegerField()
    fees = models.PositiveIntegerField()
    type = models.CharField(max_length=300)

    def get_absolute_url(self):
        return reverse("cooperate:fee_detail",kwargs={'pk':self.pk})

    def __str__(self):
        return self.course

website/cooperate/forms.py
from django import forms
from .models import centers, faculties, fee, quaries, rankers, students

class centersform(forms.Modelform):
    class meta():
        model = quaries
        fields = '__all__'

class facultiesform(forms.ModelForm):
    class meta():
        model = faculties
        fields = '__all__'
        

class feeform(forms.ModelForm):
    class meta():
        model = fee
        fields = '__all__'

class studentsform(forms.ModelForm):
    class meta():
        model = students
        fields = '__all__'

class rankersform(forms.ModelForm):
    class meta():
        model = rankers
        fields = '__all__'

class quariesform(forms.ModelForm):
    class meta():
        model = quaries
        fields = '__all__'

website/cooperate/views.py
from django.shortcuts import render
from django.views.generic import (TemplateView, ListView, DetailView, CreateView,
                                                DeleteView, UpdateView)
from django.urls import reverse_lazy, reverse
from django.contrib.auth.mixins import LoginRequiredMixin

from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.http import HttpResponseRedirect

from .models import centers, faculties, fee, quaries, rankers, students
# Create your views here.
class indexview(TemplateView):
    template_name = 'index.html'

class contactview(TemplateView):
    template_name = 'contactus.html'

class ackview(TemplateView):
    template_name = 'ack.html'

##faculties
class facultieslistview(ListView):
    context_object_name = 'faculty'
    model = faculties

class facultiesdetailview(DetailView):
    model = faculties

class facultiescreate(LoginRequiredMixin, CreateView):
    login_url = '/login/'
    redirect_field_name = 'cooperate/faculties_list.html'
    fields = '__all__'
    model = faculties

class facultiesupdate(LoginRequiredMixin, UpdateView):
    login_url = '/login/'
    redirect_field_name = 'cooperate/faculties_list.html'
    fields = '__all__'
    model = faculties

class facultiesdelete(LoginRequiredMixin, DeleteView):
    login_url = '/login/'
    redirect_field_name = 'cooperate/faculties_list.html'
    model = faculties
    success_url = reverse_lazy("cooperate:faculties_list")

##rankers

class rankerslistview(ListView):
    context_object_name = 'ranker'
    model = rankers

class rankersdetailview(DetailView):
    model = rankers

class rankerscreate(LoginRequiredMixin, CreateView):
    login_url = '/login/'
    redirect_field_name = 'cooperate/rankers_list.html'
    fields = '__all__'
    model = rankers

class rankersupdate(LoginRequiredMixin, UpdateView):
    login_url = '/login/'
    redirect_field_name = 'cooperate/rankers_list.html'
    fields = '__all__'
    model = rankers

class rankersdelete(LoginRequiredMixin, DeleteView):
    login_url = '/login/'
    redirect_field_name = 'cooperate/rankers_list.html'
    model = rankers
    success_url = reverse_lazy("cooperate:rankers_list")


##centers
class  centerslistview(ListView):
    context_object_name = 'center'
    model = centers

class  centersdetailview(DetailView):
    model = centers

class  centerscreate(LoginRequiredMixin, CreateView):
    login_url = '/login/'
    redirect_field_name = 'cooperate/centers_list.html'
    fields = '__all__'
    model = centers

class centersupdate(LoginRequiredMixin, UpdateView):
    login_url = '/login/'
    redirect_field_name = 'cooperate/centers_list.html'
    fields = '__all__'
    model = centers

class  centersdelete(LoginRequiredMixin, DeleteView):
    login_url = '/login/'
    redirect_field_name = 'cooperate/centers_list.html'
    model = centers
    success_url = reverse_lazy("cooperate:centers_list")

##students
class  studentslistview(ListView):
    context_object_name = 'student'
    model = students

class  studentsdetailview(DetailView):
    model = students

class  studentscreate(LoginRequiredMixin, CreateView):
    login_url = '/login/'
    redirect_field_name = 'cooperate/students_list.html'
    fields = '__all__'
    model = students

class studentsupdate(LoginRequiredMixin, UpdateView):
    login_url = '/login/'
    redirect_field_name = 'cooperate/students_list.html'
    fields = '__all__'
    model = students

class  studentsdelete(LoginRequiredMixin, DeleteView):
    login_url = '/login/'
    redirect_field_name = 'cooperate/students_list.html'
    model = students
    success_url = reverse_lazy("cooperate:students_list")

##fees
class  feelistview(ListView):
    context_object_name = 'fees'
    model = fee

class  feedetailview(DetailView):
    model = fee

class  feecreate(LoginRequiredMixin, CreateView):
    login_url = '/login/'
    redirect_field_name = 'cooperate/fee_list.html'
    fields = '__all__'
    model = fee

class feeupdate(LoginRequiredMixin, UpdateView):
    login_url = '/login/'
    redirect_field_name = 'cooperate/fee_list.html'
    fields = '__all__'
    model = fee

class  feedelete(LoginRequiredMixin, DeleteView):
    login_url = '/login/'
    redirect_field_name = 'cooperate/fee_list.html'
    model = fee
    success_url = reverse_lazy("cooperate:fee_list")

##quaries

class  quarieslistview(ListView):
    context_object_name = 'quary'
    model = quaries

class  quariesdetailview(DetailView):
    model = quaries

class  quariescreate(CreateView):
    fields = '__all__'
    model = quaries

class  quariesdelete(LoginRequiredMixin, DeleteView):
    login_url = '/login/'
    redirect_field_name = 'cooperate/quaries_list.html'
    model = quaries
    success_url = reverse_lazy("cooperate:quaries_list")

website/cooperate/templates/cooperate/base.html
<!DOCTYPE html>
{% load staticfiles%}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Aks Tutorials</title>
    <style media="screen">
      a{
        color:white;
      }
    </style>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link  href="{% static 'css/main.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
      <script src="{% static '/js/script.js' %}" type="text/javascript"></script>
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"> -->
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  </head>
  <body style="background:#F4F6C1; margin: 0"  >

        <nav class="navbar navbar-expand-lg techfont bg-dark  fixed-top">
          <div class="container-fluid">

<span style="color:#ffffff;"><a class='navbar-brand bigbrand' href="{% url 'cooperate:index' %}">AKS Tutorials</a></span>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
              <span class="navbar-toggler-icon" style="color:white;"><i class="fa fa-menu" >X</i></span>
            </button>
            <div class="collapse navbar-collapse" id="collapsibleNavbar">

            <ul class="nav navbar-nav">

              <li  class="nav-items"><a class="nav-link" href="{% url 'cooperate:rankers_list' %}">RANKERS</a></li>
              <li class="nav-items"><a class="nav-link" href="{% url 'cooperate:faculties_list' %}">TEAM</a></li>
              <li class="nav-items"><a  class="nav-link" href="{% url 'cooperate:centers_list' %}">CENTERS</a></li>
              <li class="nav-items"><a  class="nav-link" href="{% url 'cooperate:fee_list' %}">FEE_Details</a></li>
                {% if user.is_authenticated %}
              <li  class="nav-items"><a class="nav-link" href="{% url 'cooperate:students_list' %}">STUDENTS</a></li>
              <li  class="nav-items"><a class="nav-link" href="{% url 'cooperate:quaries_list' %}">QUARIES_ASKED</a></li>
              <li  class="nav-items"><a class="nav-link" href="{% url 'admin:index' %}">ADMIN_PANEL</a></li>
              {% else %}
                <li class="nav-items"><a  class="nav-link" href="{% url 'cooperate:contact' %}">REACH_US</a></li>

                  {% endif %}

</ul>
            <ul class="nav navbar-nav navbar-right">
              {% if user.is_authenticated %}
              <!-- <ul class="nav navbar-nav navbar-right"> -->
              <li  class="nav-items">
                <a class="nav-link" href="{% url 'logout' %}" >LOGOUT</a>
              </li>
                {% else %}
                <li  class="nav-items"><a class="nav-link" class='nav navbar-right' href="{% url 'login' %}" ><span class="glyphicon glyphicon-user"></span>LOGIN</a></li>
              {% endif %}

            </ul>


  </div>

            </div>

      </nav>

                          {% block content %}
                          {% endblock %}
</html>

website/cooperate/templates/cooperate/centers_confirm_delete.html
{% extends "cooperate/base.html" %}
{% block content %}
<div class="container" style="margin:4rem; padding-top:60px;">
<form action="" method="post">
  {% csrf_token %}
  <h4>Are you sure you want to delete "{{ centers.name }}"?</h4>
  <input class='btn btn-danger' type="submit" value="Confirm" />
</form>
</div>
{% endblock %}

website/cooperate/templates/cooperate/centers_list.html
{% extends "cooperate/base.html" %}
{% block content %}
<div class="container-fluid" style="text-align:center; padding-top:60px;">
  <h1><u><b>OUR CENTERS</b></u></h1>
  <div class="container" style="text-align:center;margin:1.2rem auto;">
  {% if user.is_authenticated %}
  <h3>Add New CENTER <button class="btn btn-success btn-large"><a href="{% url 'cooperate:centers_create' %}">ADD</a></button></h3>
  {% endif %}
  </div>
  <div class="container-fluid">
    <div class="row">
      {% for c in center %}
<div class="card col-12 col-sm-6 col-md-3" style=" border:none; width:10rem; align:center; background:#F4F6C1;">
<div class="card-body" style="padding-buttom:5px; text-align:left;">
  <ul class="list-group list-group-flush">
<li class="list-group-item" style="text-align:center;"><strong> {{ c.name }}</strong></li>
<li class="list-group-item">PLACE : {{ c.place }}</li>
  <li class="list-group-item">ADDRESS: {{ c.address }}</li>
  <li class="list-group-item">CONTACT: {{ c.contact }}</li>
  {% if user.is_authenticated %}
  <li class="list-group-item" style="text-align:center;"><button class="btn btn-warning"><a href="{% url 'cooperate:centers_update' pk=c.pk %}">UPDATE</a></button>
  <button class="btn btn-danger"><a href="{% url 'cooperate:centers_delete' pk=c.pk %}">DELETE</a></button></li>
  {% endif %}
</ul>
</div>
</div>

      {% endfor %}
    </div>
    </div>
</div>
<br><Br>
{% endblock %}

website/cooperate/templates/cooperate/faculties_form.html
{% extends 'cooperate/base.html' %}

{% block content %}
<div class="container" style="align:center;text-align:center; margin:0 auto;padding-top:60px;" >
    <h1 style="text-align:center;font-size:2em;"><u><b>Add/Update FACULTY</b></u></h1>
<br>
    <form method="POST" enctype="multipart/form-data" style="font-size:1em;">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="save btn btn-success"style="text-align:center;font-size:1em;">Save</button>
    </form>
</div>
{% endblock %}

website/cooperate/templates/cooperate/fee_detail.html
{% extends "cooperate/base.html" %}
{% block content %}
<div class="container-fluid" style="text-align:center; padding-top:15rem;">
  <div class="container">
<li class="list-group-item" style="text-align:center; width:28rem; margin:auto"><strong> {{ fee.course }}</strong></li>
<li class="list-group-item" style="text-align:center; width:28rem; margin:auto">POSITION: {{ fee.years }}</li>
<li class="list-group-item" style="text-align:center; width:28rem; margin:auto">SUBJECT: {{ fee.fees }}</li>
<li class="list-group-item" style="text-align:center; width:28rem; margin:auto">COLLEGE: {{ fee.type }}</li>
{% if user.is_authenticated %}
<li class="list-group-item" style="text-align:center; width:28rem; margin:auto"><button class="btn btn-warning"><a href="{% url 'cooperate:fee_update' pk=fee.pk %}">UPDATE</a></button>
<button class="btn btn-danger"><a href="{% url 'cooperate:fee_delete' pk=fee.pk %}">DELETE</a></button></li>
{% endif %}
</div>
</div>


    </div>
    </div>

<br><Br>
{% endblock %}

website/cooperate/templates/cooperate/fee_form.html
{% extends 'cooperate/base.html' %}

{% block content %}
<div class="container" style="align:center;text-align:center; margin:0 auto;padding-top:60px;" >
    <h1 style="text-align:center;font-size:2em;"><u><b>Add/Update FEE</b></u></h1>
<br>
    <form method="POST" enctype="multipart/form-data" style="font-size:1em;">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="save btn btn-success"style="text-align:center;font-size:1em;">Save</button>
    </form>
</div>
{% endblock %}

website/cooperate/templates/cooperate/fee_list.html
{% extends "cooperate/base.html" %}
{% block content %}
<div class="container-fluid" style="text-align:center; padding-top:60px;">
  <h1><u><b>FEE STRUCTURE</b></u></h1>
  <div class="container" style="text-align:center;margin:1.2rem auto;">
  {% if user.is_authenticated %}
  <h3>Add new FEE detials <button class="btn btn-success btn-large"><a href="{% url 'cooperate:fee_create' %}">ADD</a></button></h3>
  {% endif %}
  </div>
  <div class="container-fluid">
    <div class="row">
      {% for f in fees %}
<div class="card col-12 col-sm-6 col-md-3" style=" border:none; width:10rem; align:center; background:#F4F6C1;">
<div class="card-body" style="padding-buttom:5px; text-align:center;">
  <ul class="list-group list-group-flush">
<li class="list-group-item" style="text-align:center;"><strong> {{ f.course }}</strong></li>
<li class="list-group-item">COURSE YEARS: {{ f.years }}</li>
  <li class="list-group-item">FEE: Rs.{{ f.fees }}</li>
  <li class="list-group-item">TYPE: {{ f.type }}</li>
  {% if user.is_authenticated %}
  <li class="list-group-item" style="text-align:center;"><button class="btn btn-warning"><a href="{% url 'cooperate:fee_update' pk=f.pk %}">UPDATE</a></button>
  <button class="btn btn-danger"><a href="{% url 'cooperate:fee_delete' pk=f.pk %}">DELETE</a></button></li>
  {% endif %}
</ul>
</div>
</div>

      {% endfor %}
    </div>
    </div>
</div>
<br><Br>
{% endblock %}

website/cooperate/templates/cooperate/index.html
{% extends "cooperate/base.html" %}
{% block content %}
<div class="container-fluid" style="text-align:center; padding-top:60px;">
<div class="jumbotron" style="background:#000000; height:500px;">

</div>

</div>
<footer style="background:#000000; bottom:0;">

        <section id="contact">
          <h2>ADDRESS :- </h2>
          <h3>Contact No.:-</h3>

        </section>
</footer>
{% endblock %}

website/cooperate/templates/cooperate/quaries_confirm_delete.html
{% extends "cooperate/base.html" %}
{% block content %}
<div class="container" style="margin:4rem; padding-top:60px;">
<form action="" method="post">
  {% csrf_token %}
  <h4>Are you sure you want to delete "{{ quaries.subject }}"?</h4>
  <input class='btn btn-danger' type="submit" value="Confirm" />
</form>
</div>
{% endblock %}

website/cooperate/templates/cooperate/quaries_detail.html
{% extends "cooperate/base.html" %}
{% block content %}
<div class="container-fluid" style="text-align:center; padding-top:10rem;">
  <div class="container">
{% if user.is_authenticated %}
<li class="list-group-item" style="text-align:center; width:28rem; margin:auto">AUTHOR: <strong> {{ quaries.author }}</strong></li>
<li class="list-group-item" style="text-align:center; width:28rem; margin:auto">SUBMITTED_AT: {{ quaries.created_data }}</li>
<li class="list-group-item" style="text-align:center; width:28rem; margin:auto">SUBJECT: {{ quaries.subject }}</li>
<li class="list-group-item" style="text-align:center; width:28rem; margin:auto">EMAIL: {{ quaries.email }}</li>
<li class="list-group-item" style="text-align:center; width:28rem; margin:auto">CONTACT: {{ quaries.contact }}</li>
<li class="list-group-item" style="text-align:center; width:28rem; margin:auto">TEXT: {{ quaries.text}}</li>
<li class="list-group-item" style="text-align:center; width:28rem; margin:auto;"><button class="btn btn-primary"><a href="mailto:{{ quaries.email }}" style=" color:white;">REPLY BACK</a></button></li>
<li class="list-group-item" style="text-align:center; width:28rem; margin:auto">
<button class="btn btn-danger"><a href="{% url 'cooperate:quaries_delete' pk=quaries.pk %}" style=" color:white;">DELETE</a></button></li>
{% endif %}
</div>
</div>


    </div>
    </div>

<br><Br>
{% endblock %}

website/cooperate/templates/cooperate/rankers_detail.html
{% extends "cooperate/base.html" %}
{% block content %}
<div class="container-fluid" style="text-align:center; padding-top:60px;">
  <div class="container">
<img  class="card-img-top" src="{{ rankers.pic.url }}" style=" margin:10px; border-radius:30%; width:16rem; height:12rem;"alt="Card image cap">
<li class="list-group-item" style="text-align:center; width:28rem; margin:auto"><strong> {{ rankers.name }}</strong></li>
<li class="list-group-item" style="text-align:center; width:28rem; margin:auto">POSITION: {{ rankers.rank }}</li>
<li class="list-group-item" style="text-align:center; width:28rem; margin:auto">SUBJECT: {{ rankers.achievement }}</li>
<li class="list-group-item" style="text-align:center; width:28rem; margin:auto">COLLEGE: {{ rankers.program }}</li>
{% if user.is_authenticated %}
<li class="list-group-item" style="text-align:center; width:28rem; margin:auto"><button class="btn btn-warning"><a href="{% url 'cooperate:rankers_update' pk=rankers.pk %}">UPDATE</a></button>
<button class="btn btn-danger"><a href="{% url 'cooperate:rankers_delete' pk=rankers.pk %}">DELETE</a></button></li>
{% endif %}
</div>
</div>


    </div>
    </div>

<br><Br>
{% endblock %}

website/cooperate/templates/cooperate/students_confirm_delete.html
{% extends "cooperate/base.html" %}
{% block content %}
<div class="container" style="margin:4rem; padding-top:60px;">
<form action="" method="post">
  {% csrf_token %}
  <h4>Are you sure you want to delete "{{ students.name }}"?</h4>
  <input class='btn btn-danger' type="submit" value="Confirm" />
</form>
</div>
{% endblock %}

website/cooperate/templates/cooperate/students_form.html
{% extends 'cooperate/base.html' %}

{% block content %}
<div class="container" style="align:center;text-align:center; margin:0 auto;padding-top:60px;" >
    <h1 style="text-align:center;font-size:2em;"><u><b>Add/Update STUDENT</b></u></h1>
<br>
    <form method="POST" enctype="multipart/form-data" style="font-size:1em;">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="save btn btn-success"style="text-align:center;font-size:1em;">Save</button>
    </form>
</div>
{% endblock %}

website/cooperate/templates/cooperate/students_list.html
{% extends "cooperate/base.html" %}
{% block content %}
<div class="container-fluid" style="text-align:center; padding-top:60px;">
  <h1><u><b>OUR STUDENTS</b></u></h1>
  <div class="container" style="text-align:center;margin:1.2rem auto;">
  {% if user.is_authenticated %}
  <h3>Add New STUDENT <button class="btn btn-success btn-large"><a href="{% url 'cooperate:students_create' %}">ADD</a></button></h3>
  {% endif %}
  </div>
  <div class="container-fluid">
    <div class="row">
  {% if user.is_authenticated %}
      {% for s in student %}
<div class="card col-12 col-sm-6 col-md-4" style=" border:none; width:6rem; align:center; background:#F4F6C1;">
<img  class="card-img-top" src="{{ s.pic.url }}" style=" border-radius:30%; width:26rem; height:15rem;"alt="Card image cap">
<div class="card-body" style="padding-buttom:5px; text-align:center;">
  <ul class="list-group list-group-flush">
<li class="list-group-item" style="text-align:center;"><strong> {{ s.name }}</strong></li>
<li class="list-group-item" >FATHER'S NAME: {{ s.fathername }}</li>
<li class="list-group-item">PROGRAM: {{ s.program }}</li>
<li class="list-group-item" >CENTER: {{ s.center }}</li>

  <li class="list-group-item"><button class="btn btn-large btn-danger" style="margin:auto;"><a href="{% url 'cooperate:students_detail' pk=s.pk %}">DETAILS</a></button></li>

</ul>
</div>
</div>

      {% endfor %}
        {% endif %}
    </div>
    </div>
</div>
<br><Br>
{% endblock %}